# Generated by Django 4.2.16 on 2024-09-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'verbose_name': 'Moderator',
                'verbose_name_plural': 'Moderatorlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base_user.myuser',),
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
            ],
            options={
                'verbose_name': 'Sadə İstifadəçi',
                'verbose_name_plural': 'Sadə İstifadəçilər',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base_user.myuser',),
        ),
        migrations.AddField(
            model_name='regularusermore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regular_user_fields', to='account.regularuser'),
        ),
    ]
