version: '3.8'

services:

  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      restart: "always"
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ../nginx.conf:/etc/nginx/nginx.conf
        - ../../static:/app/static
        - ../../media:/app/media
      depends_on:
        - "web"

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: "always"
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    external:
      name: nginx-proxy
